name: Release
on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+', '[0-9]+.[0-9]+.[0-9]+-pre[0-9]+']
    paths-ignore: [ 'docs/**' ]

permissions: write-all

env:
  CONFIG: Release
  SLN_FILE: Fantastic.Avalonia.NoSamples.slnx
  MAIN_PROJ: src/Fantastic.Avalonia/Fantastic.Avalonia.fsproj
  AVALONIALABS_PROJ: extensions/Fantastic.Avalonia.Labs/Fantastic.Avalonia.Labs.fsproj
  ITEMSREPEATER_PROJ: extensions/Fantastic.Avalonia.ItemsRepeater/Fantastic.Avalonia.ItemsRepeater.fsproj
  COLORPICKER_PROJ: extensions/Fantastic.Avalonia.ColorPicker/Fantastic.Avalonia.ColorPicker.fsproj
  DATAGRID_PROJ: extensions/Fantastic.Avalonia.DataGrid/Fantastic.Avalonia.DataGrid.fsproj
  TREEDATAGRID_PROJ: extensions/Fantastic.Avalonia.TreeDataGrid/Fantastic.Avalonia.TreeDataGrid.fsproj
  DIAGNOSTICS_PROJ: extensions/Fantastic.Avalonia.Diagnostics/Fantastic.Avalonia.Diagnostics.fsproj
  TEMPLATE_PROJ: templates/Fantastic.Avalonia.Templates.proj

jobs:
  release:
    runs-on: macos-15
    environment: nuget
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Extract version from tag
      uses: damienaicheh/extract-version-from-tag-action@v1.0.0
    - name: Set release version
      run: |
        if [ "${PRE_RELEASE}" == "" ]; then
          RELEASE_VERSION=${MAJOR}.${MINOR}.${PATCH}
        else
          RELEASE_VERSION=${MAJOR}.${MINOR}.${PATCH}-${PRE_RELEASE}
        fi
        echo "Release version is $RELEASE_VERSION"
        echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_ENV"
    - name: Get Fantastic.Avalonia.Templates Changelog Entry
      id: templates_changelog
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: warn
        version: '${{ env.RELEASE_VERSION }}'
        path: templates/CHANGELOG.md
    - name: Get Fantastic.Avalonia Changelog Entry
      id: fabulous_changelog
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: warn
        version: '${{ env.RELEASE_VERSION }}'
        path: src/Fantastic.Avalonia/CHANGELOG.md
    - name: Get Fantastic.Avalonia.ItemsRepeater Changelog Entry
      id: itemsrepeater_changelog
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: warn
        version: '${{ env.RELEASE_VERSION }}'
        path: extensions/Fantastic.Avalonia.ItemsRepeater/CHANGELOG.md
    - name: Get Fantastic.Avalonia.Labs Changelog Entry
      id: avalonialabs_changelog
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: warn
        version: '${{ env.RELEASE_VERSION }}'
        path: extensions/Fantastic.Avalonia.Labs/CHANGELOG.md
    - name: Get Fantastic.Avalonia.ColorPicker Changelog Entry
      id: colorpicker_changelog
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: warn
        version: '${{ env.RELEASE_VERSION }}'
        path: extensions/Fantastic.Avalonia.ColorPicker/CHANGELOG.md
    - name: Get Fantastic.Avalonia.DataGrid Changelog Entry
      id: datagrid_changelog
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: warn
        version: '${{ env.RELEASE_VERSION }}'
        path: extensions/Fantastic.Avalonia.DataGrid/CHANGELOG.md
    - name: Get Fantastic.Avalonia.TreeDataGrid Changelog Entry
      id: treedatagrid_changelog
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: warn
        version: '${{ env.RELEASE_VERSION }}'
        path: extensions/Fantastic.Avalonia.TreeDataGrid/CHANGELOG.md
    - name: Get Fantastic.Avalonia.Diagnostics Changelog Entry
      id: diagnostics_changelog
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: warn
        version: '${{ env.RELEASE_VERSION }}'
        path: extensions/Fantastic.Avalonia.Diagnostics/CHANGELOG.md
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Install dotnet workload
      run: dotnet workload restore
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build ${SLN_FILE} -p:Version=${RELEASE_VERSION} -c ${CONFIG} --no-restore
    - name: Test
      run: dotnet test ${SLN_FILE} -p:Version=${RELEASE_VERSION} -c ${CONFIG} --no-build
    - name: Pack
      env:
        MAIN_RELEASE_NOTES: ${{ steps.fabulous_changelog.outputs.changes }}
        AVALONIALABS_RELEASE_NOTES: ${{ steps.avalonialabs_changelog.outputs.changes }}
        ITEMSREPEATER_RELEASE_NOTES: ${{ steps.itemsrepeater_changelog.outputs.changes }}
        COLORPICKER_RELEASE_NOTES: ${{ steps.colorpicker_changelog.outputs.changes }}
        DATAGRID_RELEASE_NOTES: ${{ steps.datagrid_changelog.outputs.changes }}
        TREEDATAGRID_RELEASE_NOTES: ${{ steps.treedatagrid_changelog.outputs.changes }}
        DIAGNOSTICS_RELEASE_NOTES: ${{ steps.diagnostics_changelog.outputs.changes }}
        TEMPLATES_RELEASE_NOTES: ${{ steps.templates_changelog.outputs.changes }}
      run: |
        find templates -type f -name template.json | xargs sed -i bak "s/PKG_VERSION/${RELEASE_VERSION}/g"
        PackageReleaseNotes="${MAIN_RELEASE_NOTES}" dotnet pack ${MAIN_PROJ} -p:Version=${RELEASE_VERSION} -c ${CONFIG} --property PackageOutputPath=${PWD}/nupkgs
        PackageReleaseNotes="${AVALONIALABS_RELEASE_NOTES}" dotnet pack ${AVALONIALABS_PROJ} -p:Version=${RELEASE_VERSION} -c ${CONFIG} --property PackageOutputPath=${PWD}/nupkgs
        PackageReleaseNotes="${ITEMSREPEATER_RELEASE_NOTES}" dotnet pack ${ITEMSREPEATER_PROJ} -p:Version=${RELEASE_VERSION} -c ${CONFIG} --property PackageOutputPath=${PWD}/nupkgs
        PackageReleaseNotes="${COLORPICKER_RELEASE_NOTES}" dotnet pack ${COLORPICKER_PROJ} -p:Version=${RELEASE_VERSION} -c ${CONFIG} --property PackageOutputPath=${PWD}/nupkgs
        PackageReleaseNotes="${DATAGRID_RELEASE_NOTES}" dotnet pack ${DATAGRID_PROJ} -p:Version=${RELEASE_VERSION} -c ${CONFIG} --property PackageOutputPath=${PWD}/nupkgs
        PackageReleaseNotes="${TREEDATAGRID_RELEASE_NOTES}" dotnet pack ${TREEDATAGRID_PROJ} -p:Version=${RELEASE_VERSION} -c ${CONFIG} --property PackageOutputPath=${PWD}/nupkgs
        PackageReleaseNotes="${DIAGNOSTICS_RELEASE_NOTES}" dotnet pack ${DIAGNOSTICS_PROJ} -p:Version=${RELEASE_VERSION} -c ${CONFIG} --property PackageOutputPath=${PWD}/nupkgs
        PackageReleaseNotes="${TEMPLATES_RELEASE_NOTES}" dotnet pack ${TEMPLATE_PROJ} -p:Version=${RELEASE_VERSION} -c ${CONFIG} --property PackageOutputPath=${PWD}/nupkgs
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Packages
        path: nupkgs/
    - name: Push
      run: dotnet nuget push "nupkgs/*" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }} --skip-duplicate